export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-full-stop': [2, 'never', '.'],
    'body-max-line-length': [2, 'always', Infinity],
    'body-min-length': [2, 'always', 0],
    'body-case': [2, 'always', 'lower-case'],
    'footer-leading-blank': [2, 'always'],
    'footer-max-length': [2, 'always', 72],
    'footer-max-line-length': [2, 'always', 2],
    'footer-min-length': [2, 'always', 0],
    'header-case': [2, 'always', 'lower-case'],
    'header-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    'header-min-length': [2, 'always', 0],
    'header-trim': [2, 'always'],
    'scope-enum': [2, 'always', []],
    'scope-case': [2, 'always', 'lower-case'],
    'scope-max-length': [2, 'always', Infinity],
    'scope-min-length': [2, 'always', 0],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'subject-max-length': [2, 'always', Infinity],
    'subject-min-length': [2, 'always', 0],
    'subject-exclamation-mark': [2, 'never'],
    'type-enum': [
      2,
      'always',
      ['build', 'chore', 'ci', 'docs', 'feat', 'fix', 'perf', 'refactor', 'revert', 'style', 'test'],
    ],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-max-length': [2, 'always', Infinity],
    'type-min-length': [2, 'always', 0],
  },
};
